# Generated by Django 5.1.2 on 2024-10-30 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=20)),
                ('timeCount', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notice1', models.PositiveSmallIntegerField(default=63)),
                ('notice2', models.PositiveSmallIntegerField(default=63)),
                ('notice3', models.PositiveSmallIntegerField(default=63)),
                ('notice4', models.PositiveSmallIntegerField(default=63)),
                ('notice5', models.PositiveSmallIntegerField(default=63)),
                ('notice6', models.PositiveSmallIntegerField(default=63)),
                ('notice7', models.PositiveSmallIntegerField(default=63)),
                ('notice8', models.PositiveSmallIntegerField(default=63)),
                ('notice9', models.PositiveSmallIntegerField(default=63)),
                ('notice10', models.PositiveSmallIntegerField(default=63)),
                ('notice11', models.PositiveSmallIntegerField(default=63)),
                ('notice12', models.PositiveSmallIntegerField(default=63)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector1', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector2', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector3', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector4', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector5', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector6', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector7', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector8', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector9', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector10', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector11', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector12', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
    ]
