# Generated by Django 5.1.2 on 2024-11-04 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_count_created', models.PositiveSmallIntegerField()),
                ('luminary', models.PositiveSmallIntegerField(choices=[(1, 'ASTEROID'), (2, 'MOON'), (4, 'NEBULA'), (8, 'DWARF_PLANET'), (16, 'PLANET_X'), (32, 'EMPTY_SPACE')])),
                ('sector', models.PositiveSmallIntegerField()),
                ('time_count_reviewed', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
    ]
